#!/usr/bin/python
# -*- encoding: utf-8 -*-
import unittest
import sys
import os.path
sys.path.insert(0, os.path.abspath(".."))
import data_original

class DataTestCase(unittest.TestCase):
    def _emptyLogger(self, message):
        pass

    def testDetermineDataType(self):
        data = data_original.Data()
        data.readFromCsvFile("luminance.csv", self._emptyLogger)
        self.assertEqual(data.type, data.LUMINANCE)

        for absorbanceFile in ["091221_010805_Ch1.csv",
                               "100107_015523.csv",
                               "100107_015635.csv",
                               "100108_045106.csv",
                               "100108_045630.csv",
                               "100108_045637.csv",
                               "ph1.08_330nm.csv",
                               "ph1.08_350nm.csv",
                               "ph1.08_370nm.csv",
                               "ph1.08_395nm.csv",
                               "ph1.08_405nm.csv",
                               "ph1.85_330nm.csv",
                               "ph1.85_350nm.csv",
                               "ph1.85_370nm.csv",
                               "ph1.85_395nm.csv",
                               "ph1.85_405nm.csv",
                               "ph2.67_350nm.csv",
                               "ph2.67_370nm.csv",
                               "ph2.67_395nm.csv",
                               "ph2.67_405nm.csv",
                               "ph2.67.csv"]:
            data.readFromCsvFile(absorbanceFile, self._emptyLogger)
            self.assertEqual(data.type, data.ABSORBANCE)

if __name__ == '__main__':
    unittest.main()
